export const ROW_LIST_REQUEST = 'ROW_LIST_REQUEST'
export const ROW_LIST_SUCCESS = 'ROW_LIST_SUCCESS'
export const ROW_LIST_FAIL = 'ROW_LIST_FAIL'

export const ROW_ADD_REQUEST = 'ROW_ADD_REQUEST'
export const ROW_ADD_SUCCESS = 'ROW_ADD_SUCCESS'
export const ROW_ADD_FAIL = 'ROW_ADD_FAIL'

export const ROW_EDIT_REQUEST = 'ROW_EDIT_REQUEST'
export const ROW_EDIT_SUCCESS = 'ROW_EDIT_SUCCESS'
export const ROW_EDIT_FAIL = 'ROW_EDIT_FAIL'

export const ROW_DELETE_REQUEST = 'ROW_DELETE_REQUEST'
export const ROW_DELETE_SUCCESS = 'ROW_DELETE_SUCCESS'
export const ROW_DELETE_FAIL = 'ROW_DELETE_FAIL'
